if (! this.sh_languages) {
  this.sh_languages = {};
}
sh_languages['tml'] = [
  [
    [
      /(^\t+|^ {3}|^ {6}|^ {9}|^ {12})(\*[ \t]+)(Set|Local)([\s]+)([^=]+)([ \t])(=)/g,
      ['sh_normal', 'sh_preproc', 'sh_preproc', 'sh_normal', 'sh_keyword', 'sh_normal', 'sh_normal'],
      -1
    ],
    [
      /<nop>/g,
      'sh_preproc',
      -1
    ],
    [
      /%[A-Za-z][A-Za-z0-9_:]*%/g,
      'sh_keyword',
      -1
    ],
    [
      /%(?:~~[\s]+)?[A-Za-z][A-Za-z0-9_:]*\{/g,
      'sh_keyword',
      1
    ],
    [
      /\[\[/g,
      'sh_url',
      10
    ],
    [
      /<nop>/g,
      'sh_preproc',
      -1
    ],
    [
      /[ \t]+$/g,
      'sh_whitespace',
      -1
    ],
    [
      /^---[\+#]+(?:!!)?|(?:^[\*~]~~)/g,
      'sh_preproc',
      -1
    ],
    [
      /(?:^#~~.*$)/g,
      'sh_comment',
      -1
    ],
    [
      /<\?xml/g,
      'sh_preproc',
      19,
      1
    ],
    [
      /<!DOCTYPE/g,
      'sh_preproc',
      21,
      1
    ],
    [
      /<!--/g,
      'sh_comment',
      22
    ],
    [
      /<(?:\/)?[A-Za-z](?:[A-Za-z0-9_:.-]*)(?:\/)?>/g,
      'sh_keyword',
      -1
    ],
    [
      /<(?:\/)?[A-Za-z](?:[A-Za-z0-9_:.-]*)/g,
      'sh_keyword',
      23,
      1
    ],
    [
      /&(?:[A-Za-z0-9]+);/g,
      'sh_preproc',
      -1
    ],
    [
      /<(?:\/)?[A-Za-z][A-Za-z0-9]*(?:\/)?>/g,
      'sh_keyword',
      -1
    ],
    [
      /<(?:\/)?[A-Za-z][A-Za-z0-9]*/g,
      'sh_keyword',
      23,
      1
    ]
  ],
  [
    [
      /(?:^~~~[\s]*)?\}%/g,
      'sh_keyword',
      -2
    ],
    [
      /%(?:~~[\s]+)?[A-Za-z][A-Za-z0-9_:]*\{/g,
      'sh_keyword',
      1
    ],
    [
      /[A-Za-z0-9_-]+=/g,
      'sh_attribute',
      -1
    ],
    [
      /%[A-Za-z][A-Za-z0-9_:]*%/g,
      'sh_keyword',
      -1
    ],
    [
      /%(?:~~[\s]+)?[A-Za-z][A-Za-z0-9_:]*\{/g,
      'sh_keyword',
      2
    ],
    [
      /(?:^[\*~]~~)/g,
      'sh_preproc',
      -1
    ],
    [
      /(?:^#~~.*$)/g,
      'sh_comment',
      -1
    ],
    [
      /"/g,
      'sh_string',
      18
    ]
  ],
  [
    [
      /(?:^~~~[\s]*)?\}%/g,
      'sh_keyword',
      -2
    ],
    [
      /%(?:~~[\s]+)?[A-Za-z][A-Za-z0-9_:]*\{/g,
      'sh_keyword',
      2
    ],
    [
      /[A-Za-z0-9_-]+=/g,
      'sh_attribute',
      -1
    ],
    [
      /%[A-Za-z][A-Za-z0-9_:]*%/g,
      'sh_keyword',
      -1
    ],
    [
      /%(?:~~[\s]+)?[A-Za-z][A-Za-z0-9_:]*\{/g,
      'sh_keyword',
      3
    ],
    [
      /(?:^[\*~]~~)/g,
      'sh_preproc',
      -1
    ],
    [
      /(?:^#~~.*$)/g,
      'sh_comment',
      -1
    ],
    [
      /"/g,
      'sh_string',
      13
    ]
  ],
  [
    [
      /(?:^~~~[\s]*)?\}%/g,
      'sh_keyword',
      -2
    ],
    [
      /%(?:~~[\s]+)?[A-Za-z][A-Za-z0-9_:]*\{/g,
      'sh_keyword',
      3
    ],
    [
      /[A-Za-z0-9_-]+=/g,
      'sh_attribute',
      -1
    ],
    [
      /%[A-Za-z][A-Za-z0-9_:]*%/g,
      'sh_keyword',
      -1
    ],
    [
      /"/g,
      'sh_string',
      4
    ]
  ],
  [
    [
      /\\(?:\\|")/g,
      null,
      -1
    ],
    [
      /"/g,
      'sh_string',
      -2
    ],
    [
      /%[A-Za-z][A-Za-z0-9_:]*%/g,
      'sh_keyword',
      -1
    ],
    [
      /(?:^[\*~]~~)/g,
      'sh_preproc',
      -1
    ],
    [
      /(?:^#~~.*$)/g,
      'sh_comment',
      -1
    ],
    [
      /\$perce?nt[A-Za-z][A-Za-z0-9_:]*\{?/g,
      'sh_keyword',
      5
    ],
    [
      /(\$[a-zA-Z0-9_]+\()([^\)]*)(\))/g,
      ['sh_function', 'sh_usertype', 'sh_function'],
      -1
    ],
    [
      /(\$[a-zA-Z0-9_]+)/g,
      ['sh_function'],
      -1
    ],
    [
      /\[\[/g,
      'sh_url',
      7
    ]
  ],
  [
    [
      /\}?\$perce?nt/g,
      'sh_keyword',
      -2
    ],
    [
      /\$perce?nt[A-Za-z][A-Za-z0-9_:]*\{?/g,
      'sh_keyword',
      5
    ],
    [
      /[A-Za-z0-9_-]+=/g,
      'sh_attribute',
      -1
    ],
    [
      /%[A-Za-z][A-Za-z0-9_:]*%/g,
      'sh_keyword',
      -1
    ],
    [
      /\\"/g,
      'sh_string',
      6
    ],
    [
      /(\$[a-zA-Z0-9_]+\()([^\)]*)(\))/g,
      ['sh_function', 'sh_usertype', 'sh_function'],
      -1
    ],
    [
      /(\$[a-zA-Z0-9_]+)/g,
      ['sh_function'],
      -1
    ]
  ],
  [
    [
      /\\\\(?:\\\\|\\")/g,
      null,
      -1
    ],
    [
      /\\"/g,
      'sh_string',
      -2
    ],
    [
      /%[A-Za-z][A-Za-z0-9_:]*%/g,
      'sh_keyword',
      -1
    ],
    [
      /(\$[a-zA-Z0-9_]+\()([^\)]*)(\))/g,
      ['sh_function', 'sh_usertype', 'sh_function'],
      -1
    ],
    [
      /(\$[a-zA-Z0-9_]+)/g,
      ['sh_function'],
      -1
    ],
    [
      /\[\[/g,
      'sh_url',
      7
    ],
    [
      /\[\[/g,
      'sh_url',
      10
    ],
    [
      /<nop>/g,
      'sh_preproc',
      -1
    ],
    [
      /[ \t]+$/g,
      'sh_whitespace',
      -1
    ],
    [
      /^---[\+#]+(?:!!)?|(?:^[\*~]~~)/g,
      'sh_preproc',
      -1
    ],
    [
      /(?:^#~~.*$)/g,
      'sh_comment',
      -1
    ]
  ],
  [
    [
      /\]\]/g,
      'sh_url',
      -2
    ],
    [
      /%[A-Za-z][A-Za-z0-9_:]*%/g,
      'sh_keyword',
      -1
    ],
    [
      /%(?:~~[\s]+)?[A-Za-z][A-Za-z0-9_:]*\{/g,
      'sh_keyword',
      8
    ],
    [
      /(\$[a-zA-Z0-9_]+\()([^\)]*)(\))/g,
      ['sh_function', 'sh_usertype', 'sh_function'],
      -1
    ],
    [
      /(\$[a-zA-Z0-9_]+)/g,
      ['sh_function'],
      -1
    ]
  ],
  [
    [
      /(?:^~~~[\s]*)?\}%/g,
      'sh_keyword',
      -2
    ],
    [
      /%(?:~~[\s]+)?[A-Za-z][A-Za-z0-9_:]*\{/g,
      'sh_keyword',
      8
    ],
    [
      /%[A-Za-z][A-Za-z0-9_:]*%/g,
      'sh_keyword',
      -1
    ],
    [
      /[A-Za-z0-9_-]+=/g,
      'sh_attribute',
      -1
    ],
    [
      /"/g,
      'sh_string',
      9
    ]
  ],
  [
    [
      /\\(?:\\|")/g,
      null,
      -1
    ],
    [
      /"/g,
      'sh_string',
      -2
    ],
    [
      /<nop>/g,
      'sh_preproc',
      -1
    ],
    [
      /[ \t]+$/g,
      'sh_whitespace',
      -1
    ],
    [
      /^---[\+#]+(?:!!)?|(?:^[\*~]~~)/g,
      'sh_preproc',
      -1
    ],
    [
      /(?:^#~~.*$)/g,
      'sh_comment',
      -1
    ]
  ],
  [
    [
      /\]\]/g,
      'sh_url',
      -2
    ],
    [
      /%[A-Za-z][A-Za-z0-9_:]*%/g,
      'sh_keyword',
      -1
    ],
    [
      /%(?:~~[\s]+)?[A-Za-z][A-Za-z0-9_:]*\{/g,
      'sh_keyword',
      11
    ],
    [
      /<nop>/g,
      'sh_preproc',
      -1
    ],
    [
      /[ \t]+$/g,
      'sh_whitespace',
      -1
    ],
    [
      /^---[\+#]+(?:!!)?|(?:^[\*~]~~)/g,
      'sh_preproc',
      -1
    ],
    [
      /(?:^#~~.*$)/g,
      'sh_comment',
      -1
    ]
  ],
  [
    [
      /(?:^~~~[\s]*)?\}%/g,
      'sh_keyword',
      -2
    ],
    [
      /%(?:~~[\s]+)?[A-Za-z][A-Za-z0-9_:]*\{/g,
      'sh_keyword',
      11
    ],
    [
      /%[A-Za-z][A-Za-z0-9_:]*%/g,
      'sh_keyword',
      -1
    ],
    [
      /[A-Za-z0-9_-]+=/g,
      'sh_attribute',
      -1
    ],
    [
      /"/g,
      'sh_string',
      12
    ]
  ],
  [
    [
      /\\(?:\\|")/g,
      null,
      -1
    ],
    [
      /"/g,
      'sh_string',
      -2
    ],
    [
      /(\$[a-zA-Z0-9_]+\()([^\)]*)(\))/g,
      ['sh_function', 'sh_usertype', 'sh_function'],
      -1
    ],
    [
      /(\$[a-zA-Z0-9_]+)/g,
      ['sh_function'],
      -1
    ]
  ],
  [
    [
      /\\(?:\\|")/g,
      null,
      -1
    ],
    [
      /"/g,
      'sh_string',
      -2
    ],
    [
      /%[A-Za-z][A-Za-z0-9_:]*%/g,
      'sh_keyword',
      -1
    ],
    [
      /%(?:~~[\s]+)?[A-Za-z][A-Za-z0-9_:]*\{/g,
      'sh_keyword',
      3
    ],
    [
      /\$perce?nt[A-Za-z][A-Za-z0-9_:]*\{?/g,
      'sh_keyword',
      14
    ],
    [
      /(\$[a-zA-Z0-9_]+\()([^\)]*)(\))/g,
      ['sh_function', 'sh_usertype', 'sh_function'],
      -1
    ],
    [
      /(\$[a-zA-Z0-9_]+)/g,
      ['sh_function'],
      -1
    ],
    [
      /\[\[/g,
      'sh_url',
      7
    ],
    [
      /\[\[/g,
      'sh_url',
      10
    ],
    [
      /<nop>/g,
      'sh_preproc',
      -1
    ],
    [
      /[ \t]+$/g,
      'sh_whitespace',
      -1
    ],
    [
      /^---[\+#]+(?:!!)?|(?:^[\*~]~~)/g,
      'sh_preproc',
      -1
    ],
    [
      /(?:^#~~.*$)/g,
      'sh_comment',
      -1
    ]
  ],
  [
    [
      /\}?\$perce?nt/g,
      'sh_keyword',
      -2
    ],
    [
      /\$perce?nt[A-Za-z][A-Za-z0-9_:]*\{?/g,
      'sh_keyword',
      14
    ],
    [
      /[A-Za-z0-9_-]+=/g,
      'sh_attribute',
      -1
    ],
    [
      /%[A-Za-z][A-Za-z0-9_:]*%/g,
      'sh_keyword',
      -1
    ],
    [
      /%(?:~~[\s]+)?[A-Za-z][A-Za-z0-9_:]*\{/g,
      'sh_keyword',
      3
    ],
    [
      /\$perce?nt[A-Za-z][A-Za-z0-9_:]*\{?/g,
      'sh_keyword',
      15
    ],
    [
      /\\"/g,
      'sh_string',
      17
    ],
    [
      /(\$[a-zA-Z0-9_]+\()([^\)]*)(\))/g,
      ['sh_function', 'sh_usertype', 'sh_function'],
      -1
    ],
    [
      /(\$[a-zA-Z0-9_]+)/g,
      ['sh_function'],
      -1
    ]
  ],
  [
    [
      /\}?\$perce?nt/g,
      'sh_keyword',
      -2
    ],
    [
      /\$perce?nt[A-Za-z][A-Za-z0-9_:]*\{?/g,
      'sh_keyword',
      15
    ],
    [
      /[A-Za-z0-9_-]+=/g,
      'sh_attribute',
      -1
    ],
    [
      /%[A-Za-z][A-Za-z0-9_:]*%/g,
      'sh_keyword',
      -1
    ],
    [
      /%(?:~~[\s]+)?[A-Za-z][A-Za-z0-9_:]*\{/g,
      'sh_keyword',
      3
    ],
    [
      /\$perce?nt[A-Za-z][A-Za-z0-9_:]*\{?/g,
      'sh_keyword',
      5
    ],
    [
      /\\"/g,
      'sh_string',
      16
    ],
    [
      /(\$[a-zA-Z0-9_]+\()([^\)]*)(\))/g,
      ['sh_function', 'sh_usertype', 'sh_function'],
      -1
    ],
    [
      /(\$[a-zA-Z0-9_]+)/g,
      ['sh_function'],
      -1
    ]
  ],
  [
    [
      /\\\\(?:\\\\|\\")/g,
      null,
      -1
    ],
    [
      /\\"/g,
      'sh_string',
      -2
    ],
    [
      /%[A-Za-z][A-Za-z0-9_:]*%/g,
      'sh_keyword',
      -1
    ],
    [
      /%(?:~~[\s]+)?[A-Za-z][A-Za-z0-9_:]*\{/g,
      'sh_keyword',
      3
    ],
    [
      /\$perce?nt[A-Za-z][A-Za-z0-9_:]*\{?/g,
      'sh_keyword',
      5
    ],
    [
      /(\$[a-zA-Z0-9_]+\()([^\)]*)(\))/g,
      ['sh_function', 'sh_usertype', 'sh_function'],
      -1
    ],
    [
      /(\$[a-zA-Z0-9_]+)/g,
      ['sh_function'],
      -1
    ],
    [
      /\[\[/g,
      'sh_url',
      7
    ],
    [
      /\[\[/g,
      'sh_url',
      10
    ],
    [
      /<nop>/g,
      'sh_preproc',
      -1
    ],
    [
      /[ \t]+$/g,
      'sh_whitespace',
      -1
    ],
    [
      /^---[\+#]+(?:!!)?|(?:^[\*~]~~)/g,
      'sh_preproc',
      -1
    ],
    [
      /(?:^#~~.*$)/g,
      'sh_comment',
      -1
    ]
  ],
  [
    [
      /\\\\(?:\\\\|\\")/g,
      null,
      -1
    ],
    [
      /\\"/g,
      'sh_string',
      -2
    ],
    [
      /%[A-Za-z][A-Za-z0-9_:]*%/g,
      'sh_keyword',
      -1
    ],
    [
      /%(?:~~[\s]+)?[A-Za-z][A-Za-z0-9_:]*\{/g,
      'sh_keyword',
      3
    ],
    [
      /\$perce?nt[A-Za-z][A-Za-z0-9_:]*\{?/g,
      'sh_keyword',
      15
    ],
    [
      /(\$[a-zA-Z0-9_]+\()([^\)]*)(\))/g,
      ['sh_function', 'sh_usertype', 'sh_function'],
      -1
    ],
    [
      /(\$[a-zA-Z0-9_]+)/g,
      ['sh_function'],
      -1
    ],
    [
      /\[\[/g,
      'sh_url',
      7
    ],
    [
      /\[\[/g,
      'sh_url',
      10
    ],
    [
      /<nop>/g,
      'sh_preproc',
      -1
    ],
    [
      /[ \t]+$/g,
      'sh_whitespace',
      -1
    ],
    [
      /^---[\+#]+(?:!!)?|(?:^[\*~]~~)/g,
      'sh_preproc',
      -1
    ],
    [
      /(?:^#~~.*$)/g,
      'sh_comment',
      -1
    ]
  ],
  [
    [
      /\\(?:\\|")/g,
      null,
      -1
    ],
    [
      /"/g,
      'sh_string',
      -2
    ],
    [
      /%[A-Za-z][A-Za-z0-9_:]*%/g,
      'sh_keyword',
      -1
    ],
    [
      /%(?:~~[\s]+)?[A-Za-z][A-Za-z0-9_:]*\{/g,
      'sh_keyword',
      2
    ],
    [
      /\$perce?nt[A-Za-z][A-Za-z0-9_:]*\{?/g,
      'sh_keyword',
      14
    ],
    [
      /(\$[a-zA-Z0-9_]+\()([^\)]*)(\))/g,
      ['sh_function', 'sh_usertype', 'sh_function'],
      -1
    ],
    [
      /(\$[a-zA-Z0-9_]+)/g,
      ['sh_function'],
      -1
    ],
    [
      /\[\[/g,
      'sh_url',
      7
    ],
    [
      /\[\[/g,
      'sh_url',
      10
    ],
    [
      /<nop>/g,
      'sh_preproc',
      -1
    ],
    [
      /[ \t]+$/g,
      'sh_whitespace',
      -1
    ],
    [
      /^---[\+#]+(?:!!)?|(?:^[\*~]~~)/g,
      'sh_preproc',
      -1
    ],
    [
      /(?:^#~~.*$)/g,
      'sh_comment',
      -1
    ]
  ],
  [
    [
      /\?>/g,
      'sh_preproc',
      -2
    ],
    [
      /([^=" \t>]+)([ \t]*)(=?)/g,
      ['sh_type', 'sh_normal', 'sh_symbol'],
      -1
    ],
    [
      /"/g,
      'sh_string',
      20
    ]
  ],
  [
    [
      /\\(?:\\|")/g,
      null,
      -1
    ],
    [
      /"/g,
      'sh_string',
      -2
    ]
  ],
  [
    [
      />/g,
      'sh_preproc',
      -2
    ],
    [
      /([^=" \t>]+)([ \t]*)(=?)/g,
      ['sh_type', 'sh_normal', 'sh_symbol'],
      -1
    ],
    [
      /"/g,
      'sh_string',
      20
    ]
  ],
  [
    [
      /-->/g,
      'sh_comment',
      -2
    ],
    [
      /<!--/g,
      'sh_comment',
      22
    ]
  ],
  [
    [
      /(?:\/)?>/g,
      'sh_keyword',
      -2
    ],
    [
      /([^=" \t>]+)([ \t]*)(=?)/g,
      ['sh_type', 'sh_normal', 'sh_symbol'],
      -1
    ],
    [
      /"/g,
      'sh_string',
      20
    ]
  ]
];
